name: cloudwrite
description: CloudWrite Flutter application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.10.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: 1.0.0
  fluro: ^1.7.8
  dio: ^3.0.10
  rxdart: 0.24.0
  json_serializable: ^3.5.1
  json_annotation: ^3.1.1
  logger: ^0.9.4
  get_it: ^5.0.6
  pedantic: ^1.9.2
  mockito: ^4.1.4
  flutter_translate: ^1.6.0
  flutter_secure_storage: 3.3.1
  smart_select: ^4.3.2
  bloc: ^6.1.1
  equatable: ^1.2.5
  formz: ^0.3.2
  flutter_bloc: ^6.1.1
  graphql_flutter: 3.1.0
  jwt_decoder: ^1.0.4
  flutter_tags: ^0.4.9+1
  flutter_search_bar: ^2.1.0
  easy_debounce: ^1.0.2
  waterfall_flow: any
  list_tile_switch: ^0.0.2
  pull_to_refresh: 1.6.3
  glutton: ^1.0.5
  flutter_gherkin: ^1.1.9
  glob: ^1.2.0

dev_dependencies:
  build_runner: ^1.11.0
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: ^1.15.7

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/localization/
